version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    container_name: db
  uwsgi:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"
    container_name: uwsgi
  nginx:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - uwsgi
    container_name: nginx