version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: db_name
    container_name: db
    networks:
      - my-network
  uwsgi:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"
    container_name: uwsgi
    networks:
      - my-network
  nginx:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - uwsgi
    container_name: nginx
    environment:
      TZ: "Asia/Tokyo"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge